version: '3.8'

services:
  postgres:
    build:
      context: ./docker
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    command: --max_prepared_transactions=5
